name: Reusable deploy
on: 
    workflow_call:
        inputs:
            artifact-name:
                description: The name of the deployable artifact
                required: false
                default: dist
                type: string
        outputs:
            result:
                description: Output reusable deploy
                value: ${{ jobs.deploy.outputs.outcome }}
jobs:
    deploy:
        outputs:
            outcome: ${{ steps.set-result.outputs.step-result }}
        runs-on: ubuntu-20.04
        steps:
            - name: Get code
              uses: actions/download-artifact@v3
              with:
                name: ${{ inputs.artifact-name }}
            - name: List files
              run: ls
            - name: Output info
              run: echo "Simulating deploying"
            - name: Set result output
              id: set-result
              run: echo "step-result=success" >> $GITHUB_OUTPUT